# VHS v0.11.0

# Tokyo Night variants in VHS (background):
# TokyoNight       #16161e
# tokyonight       #1a1b26
# tokyonight-storm #24283b
# TokyoNightStorm  #1f2335

Output profile.gif

Set Shell bash
Set Theme "tokyonight"
Set MarginFill "#1a1b26"

Set FontFamily "JetBrainsMono Nerd Font Mono"
Set FontSize 18
Set Width 1200
Set Height 800
Set Padding 0
Set Margin 24
Set TypingSpeed 1ms

Type "bash git-fetch.sh"
Sleep 2s
Enter
Sleep 30s
